public class AnimalLocator {
	
    public static String getAnimalNameById(Integer paramFirst){
        String returned = '';
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://th-apex-http-callout.herokuapp.com/animals/'+paramFirst);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if (response.getStatusCode() == 200) {
            Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            Map<String,Object> animal = (Map<String,Object>) results.get('animal');
            returned = (String)animal.get('name'); 
        }
        
        return returned;
    }
}